_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: ".output/pretrain/model_0449999.pth"
  SWINTS:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 2
  REC_HEAD:
      POOLER_RESOLUTION: (16,48)
      RESOLUTION: (32, 96)
      BATCH_SIZE: 1
DATASETS:
  TRAIN: ("ctw1500_train",)
  TEST:  ("ctw1500_test",)
SOLVER:
  STEPS: (360000,420000)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 1000
INPUT:
  FORMAT: "RGB"
